// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5E6eoTfxlLVl8J3AcqSwi4CLurWYtKmE',
    appId: '1:828780416825:web:577b1e448112b84cefa2e8',
    messagingSenderId: '828780416825',
    projectId: 'iau-document',
    authDomain: 'iau-document.firebaseapp.com',
    storageBucket: 'iau-document.firebasestorage.app',
    measurementId: 'G-HNG4W11J33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmXHEX85KIw3u9t332Uk9JlZOgGOWD_1g',
    appId: '1:828780416825:android:31dbc66000c219d6efa2e8',
    messagingSenderId: '828780416825',
    projectId: 'iau-document',
    storageBucket: 'iau-document.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsY7DcmOFVQgmQTohrlhx8um6DTrA3uW8',
    appId: '1:828780416825:ios:2b034b42ce6415f5efa2e8',
    messagingSenderId: '828780416825',
    projectId: 'iau-document',
    storageBucket: 'iau-document.firebasestorage.app',
    iosBundleId: 'com.example.flutterLoginPage',
  );
}
